version: 2
updates:
  - package-ecosystem: "maven"
    # Look for `pom.xml` in the `root` directory. It will recursively scan any submodules.
    directory: "/"
    schedule:
      # Check for updates once a day. This can be changed later on to `weekly` if desired.
      interval: "monthly"
    # Add reviewers
    reviewers:
      - "corona-warn-app/cwa-server-codeowners"
