version: 2.1
jobs:
  build:
    working_directory: ~/cwa-server
    machine:
      image: ubuntu-2004:202101-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Update to OpenJDK 11
          command: |
            sudo apt-get install openjdk-11-jre
            sudo update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
            java -version
      - run:
          name: Generate cumulative pom.xml checksum
          command: |
            find . -type f -name "pom.xml" -exec sh -c "sha256sum {} >> ~/pom-checksum.tmp" \;
            sort -o ~/pom-checksum ~/pom-checksum.tmp
          when: always
      - restore_cache:
          key: cwa-server-{{ checksum "~/pom-checksum" }}
      - run: ./mvnw --batch-mode dependency:go-offline
      - run:
          name: JUnit Tests, Integration Tests
          command: |
            export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
            ./mvnw --batch-mode -P integration-test verify --fail-fast
      - run:
          name: Analyze on SonarCloud
          command: |
            export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
            ./mvnw --batch-mode sonar:sonar --fail-never
      - save_cache:
          paths:
            - ~/.m2
          key: cwa-server-{{ checksum "~/pom-checksum" }}
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
      - run:
          command: cat /sys/fs/cgroup/memory/memory.max_usage_in_bytes
          when: always

workflows:
  circleci:
    jobs:
      - build:
          context: SonarCloud
