---
logging:
  level:
    org:
      springframework:
        web: INFO
    app:
      coronawarn: INFO

services:
  distribution:
    output-file-name: index
    retention-days: 14
    expiry-policy-minutes: 120
    shifting-policy-threshold: 140
    include-incomplete-days: false
    include-incomplete-hours: false
    paths:
      output: out
      privatekey: ${VAULT_FILESIGNING_SECRET}
    tek-export:
      file-name: export.bin
      file-header: EK Export v1
      file-header-width: 16
    api:
      version-path: version
      version-v1: v1
      country-path: country
      country-germany: DE
      date-path: date
      hour-path: hour
      diagnosis-keys-path: diagnosis-keys
      parameters-path: configuration
      app-config-file-name: app_config
    signature:
      verification-key-id: 262
      verification-key-version: v1
      algorithm-oid: 1.2.840.10045.4.3.2
      algorithm-name: SHA256withECDSA
      file-name: export.sig
      security-provider: BC
    # Configuration for the S3 compatible object storage hosted by Telekom in Germany
    objectstore:
      access-key: ${CWA_OBJECTSTORE_ACCESSKEY:accessKey1}
      secret-key: ${CWA_OBJECTSTORE_SECRETKEY:verySecretKey1}
      endpoint: ${CWA_OBJECTSTORE_ENDPOINT:http://localhost}
      bucket: ${CWA_OBJECTSTORE_BUCKET:cwa}
      port: ${CWA_OBJECTSTORE_PORT:8003}
      set-public-read-acl-on-put-object: true
      retry-attempts: 3
      retry-backoff: 2000
      max-number-of-failed-operations: 5

spring:
  main:
    web-application-type: NONE
# Postgres configuration
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration/postgres
    password: ${POSTGRESQL_PASSWORD_FLYWAY:postgres}
    user: ${POSTGRESQL_USER_FLYWAY:postgres}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRESQL_SERVICE_HOST:localhost}:${POSTGRESQL_SERVICE_PORT:5432}/${POSTGRESQL_DATABASE:cwa}
    username: ${POSTGRESQL_USER_DISTRIBUTION:postgres}
    password: ${POSTGRESQL_PASSWORD_DISTRIBUTION:postgres}
