name: license-analysis-workflow

on:
    pull_request:
        branches: [ main, release/** ]
        branches-ignore: gh-pages

jobs:
    license-analysis-job:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -   name: REUSE Compliance Check
            uses: fsfe/reuse-action@v1.1