name: markdown-analysis-workflow

on:
    pull_request:
        branches:
        - main
        - release/**
        paths:
        - '**/*.md'

jobs:
    markdown-analysis-job:
        runs-on: ubuntu-latest
        name: 'github actions: markdownlint'
        steps:
        -   uses: actions/checkout@v2
        -   name: markdownlint
            uses: nosborn/github-action-markdown-cli@v1.1.1
            with:
                files: .
                config_file: ./codestyle/.markdownlint.yml